(load (concat default-directory "syncthing.el"))
(defun syncthing-demo (name addr)
  (dolist (_ (number-sequence 1 30))
    (sleep-for 0.1))
  (syncthing-with-base name addr "dummy-token")
  (end-of-buffer)
  (save-window-excursion
    (beginning-of-buffer)
    (let (buf)
      (dolist (item (buffer-list))
        (when (and (string-match (regexp-quote name) (buffer-name item))
                   (not buf))
          (setq buf item)))
      (switch-to-buffer buf)
      (while (string= "" (buffer-string))
        (sleep-for 0.01))
      (syncthing-auto-refresh-mode 0)
      (goto-char 0)
      (dolist (_ (number-sequence 1 8))
        (next-line))
      (dolist (_ (number-sequence 1 3))
        (syncthing--newline (point))
        (previous-line))
      (dolist (_ (number-sequence 1 3))
        (previous-line))
      (syncthing--newline (point))
      (previous-line)
      (syncthing--newline (point))
      (menu-bar-mode 0)
      (toggle-frame-fullscreen)
      (text-scale-adjust -1)
      (message "Demo layout done"))))
