(setq-local load-path (push default-directory load-path))
(load (concat default-directory "syncthing.el"))
(defun syncthing-demo (name addr)
  (dotimes (_ 30) (sleep-for 0.1))
  (let ((syncthing-debug t))
    (syncthing-with-base name addr "dummy-token")
    (setq syncthing-debug nil)
    (call-interactively 'end-of-buffer)
    (save-window-excursion
      (call-interactively 'beginning-of-buffer)
      (let (buf)
        (dolist (item (buffer-list))
          (when (and (string-match (regexp-quote name) (buffer-name item))
                     (not buf))
            (setq buf item)))
        (switch-to-buffer buf)
        (while (string= "" (buffer-string))
          (sleep-for 0.01))
        (syncthing-auto-refresh-mode 0)
        (goto-char 0)
        (dotimes (_ 8) (call-interactively 'next-line))
        (dotimes (_ 3)
          (execute-kbd-macro (kbd "RET"))
          (call-interactively 'previous-line))
        (dotimes (_ 3) (call-interactively 'previous-line))
        (execute-kbd-macro (kbd "RET"))
        (call-interactively 'previous-line)
        (execute-kbd-macro (kbd "RET"))
        (menu-bar-mode 0)
        (toggle-frame-fullscreen)
        (text-scale-adjust -1)
        (message "Demo layout done")))))
